### ISSUE TITLE
Server Stalls/becomes Unresponsive, no crash report but players can't connect.

### ISSUE THREAD

**Issue by katubug** [adam9899/Issues#106]
Hey! So this has been happening to us for a while since installing the pack. I've asked about it in Discord once or twice but haven't had any response as to whether this is a known issue or not.

Basically, once or twice a day, the whole server stalls out. Sometimes it generates a stall report (from the Sampler server utility), sometimes not. It never produces a crash report. Most times, the server requires me to Kill it, and then Start. However, other times the server goes completely offline and I only need to Start.

Here is my latest.log from the most recent time: https://paste.ee/p/623Kj

The debug.log is too big even for paste.ee, but here's an excerpt. It's mostly this exact error, just repeated for hundreds of lines:
```
[09:53:09] [Netty Server IO #3/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:1.8.0_212]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:1.8.0_212]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.8.0_212]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[?:1.8.0_212]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

We tried the netty fix as listed in this thread: https://github.com/SpongePowered/SpongeForge/issues/2625

We don't use spongeforge, however, so I have not disabled swap memory, as I'm not sure it would be effective, and my server host advised against it. We run a dedicated server, Linux-based, with the Pterodactyl panel. We have 16gb RAM (of which 10gb is allocated) and plenty of disk space.

We have 4 scheduled restarts a day, at 10am/pm and 4am/pm. This error does not seem to occur at any specific time, as sometimes it's a few hours after a restart, but other times it's only minutes after a restart.

**Comment by beironjohn** [comment]
I know sometimes this is caused (or has at least happened when) when a user starts the connection to the server, and then clicks the cancel button (i.e. when my wife shouts at me for something so i cancel the login using the UI button).

This has happened, in my case, once or twice, but have experienced the timeout whilst playing as well.

From a user POV while playing, the game remains responsive, to the point you can move, interact with inventories, etc  - nothing seems to be wrong - then within 30 - 60 secs we get disconnected with a "timed out" message. The server becomes unavailable from the multiplayer menu, until Katu brings out the spanner of +5 fixing (does the back end server restarts).

**Comment by adam9899** [comment]
Has the issue happened since? 

-Adam

**Comment by katubug** [comment]
It seems to be happening less often, but yeah it has happened since I wrote this report. Previously it was on average 1.5 times a day, now it's more like once every 2 days or so.

The changes we've made since the initial report are:
- We updated the pack, obviously. :P 
- We set up an automatically fired command via WorldPrimer that every 30 minutes clears: Unnamed Rats, Unnamed Quark Frogs, dropped items, and other hostiles.
- We configured our backups to occur hourly instead of every half hour. Additionally, I set it to only back up the overworld and the Compact Machines dimension, so the backups take less time. 
- We experienced some data loss, and replaced forge's libraries, the forge jar, and the vanilla server jar.

There were other small tweaks, but unfortunately I didn't note them down.

**Comment by adam9899** [comment]
I've received multiple reports about something similar and strangely enough removing the lines in the Wizardry config that refer to Arcane Essentials seemed to anecdotally fix 2 servers. I haven't been able to fully test it myself yet but here's a fresh Wizardry config with Arcane Essentials removed. https://cdn.discordapp.com/attachments/665965547837718540/668501008879452170/ebwizardry.cfg

**Comment by katubug** [comment]
Ah, gotcha! That makes sense in a weird way. I'll get that uploaded shortly.

**Comment by katubug** [comment]
Okay, it's set. I'll check back with you if the crashes continue. Also, a minor note about the config you linked seems to be missing some of the changes you made to the original, such as allowing towers and world gen in other dimensions.

**Comment by katubug** [comment]
Hey, just wanted to update - this seems to still be happening. It has tried to produce a crash report a couple of times, but they're just empty files.

They also seem to have resulted in catastrophic data loss (ie, I had to reupload forge/libraries, all mods and all configs just to get the server to restart - FTBU ranks also get erased), about 3-4 times now. I'm not sure if it's occurring during a backup or something? And since the changelogs are blank, and the log files just cut off, I don't really have any leads on this.

I'll keep looking though! Just wanted to keep this up-to-date. Thanks for your time!
