### ISSUE TITLE
Server crashes on NBT write from certain players.

### ISSUE THREAD

**Issue by wezu123** [adam9899/Issues#118]
We've been playing our world a few days now, and we have encountered a bug yesterday. A few players were crashing the server, it was happening when:
- a defective player was playing for some time on the server
- a defective player disconnected and joined the server back

The crashlog is just the usual watchdog timeout, however my console reports some NBT write problems:

`[13:01:08] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.StackOverflowError
[13:01:08] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.io.DataOutputStream.write(DataOutputStream.java:107)
[13:01:08] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:401)
[13:01:08] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
[13:01:08] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474)
[13:01:08] [File IO Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35)`

Repeated a couple dozen times.

`[13:20:59] [Netty Epoll Server IO #9/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.EncoderException: java.lang.StackOverflowError
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:548) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.StackOverflowError
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:270) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:265) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1036) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.network.PacketBuffer.writeBytes(PacketBuffer.java:1114) ~[gy.class:?]
	at io.netty.buffer.ByteBufOutputStream.write(ByteBufOutputStream.java:66) ~[minecraft_server.1.12.2.jar:?]
	at java.io.DataOutputStream.write(DataOutputStream.java:107) ~[?:1.8.0_191]
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:401) ~[?:1.8.0_191]
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323) ~[?:1.8.0_191]
	at io.netty.buffer.ByteBufOutputStream.writeUTF(ByteBufOutputStream.java:137) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.nbt.NBTTagCompound.writeEntry(NBTTagCompound.java:474) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.write(NBTTagCompound.java:35) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.writeEntry(NBTTagCompound.java:475) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.write(NBTTagCompound.java:35) ~[fy.class:?]`

Same case here. We've managed to eliminate the problem with two players (not 100% sure, but they haven't crashed yet), but one player is still crashing the server. It seems that certain items cause that problem.

Complete server log available here: https://drive.google.com/open?id=1e_mhHOamOqHl8ckkF-ytM_e29rsipm4x
Posted it on Google Drive since Pastebin doesn't allow for files over 512KB.

**Comment by lagrd2** [comment]
I had the same issue on the server I'm hosting for friends. I've had the errors appear for some users and not crash the server, and at other times the errors will appear and crash the server immediately. The last time it occurred we were able to replicate the errors and crash 3 times in a row. It was related to a player placing and opening his backpack (the first backpack in the quest book). At the time I was much less interested in what was in the backpack or why it was happening, I just informed the players to avoid the backpacks till further notice and disposed of his bugged backpack. I'm not sure if this is the only reason for the errors, but I have not seen the errors since we have discontinued the use of the backpacks. 

Hope this helps!

**Comment by ByteTemplar** [comment]
You can place the backpack in Bauble slot and open it with keybind btw, no need to place on ground to use...
Dunno if it helps on the problem though, if the use of backpack is giving errors, maybe test.
