### ISSUE TITLE
Loot Games minesweeper cannot be played in multiplayer

### ISSUE THREAD

**Issue by CptPatate** [adam9899/Issues#129]
Hello, i found a dungeon on my server, lastest version I can start the minesweepergame put it cannot be played it just launch this error into the log : 

[15:24:59] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: cFlaggedFields
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_221]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_221]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchFieldError: cFlaggedFields
        at ru.timeconqueror.lootgames.minigame.minesweeper.MSBoard.<init>(MSBoard.java:21) ~[MSBoard.class:?]
        at ru.timeconqueror.lootgames.minigame.minesweeper.GameMineSweeper.<init>(GameMineSweeper.java:60) ~[GameMineSweeper.class:?]
        at ru.timeconqueror.lootgames.minigame.minesweeper.tileentity.TileEntityMSMaster.<init>(TileEntityMSMaster.java:17) ~[TileEntityMSMaster.class:?]
        at ru.timeconqueror.lootgames.minigame.minesweeper.block.BlockMSMaster.createTileEntity(BlockMSMaster.java:19) ~[BlockMSMaster.class:?]
        at net.minecraft.world.chunk.Chunk.createNewTileEntity(Chunk.java:782) ~[axw.class:?]
        at net.minecraft.world.chunk.Chunk.getTileEntity(Chunk.java:800) ~[axw.class:?]
        at net.minecraft.world.World.getTileEntity(World.java:2402) ~[amu.class:?]
        at ru.timeconqueror.lootgames.api.block.BlockSmartSubordinate.getMasterPos(BlockSmartSubordinate.java:87) ~[BlockSmartSubordinate.class:?]
        at ru.timeconqueror.lootgames.api.block.BlockSmartSubordinate.onBlockActivated(BlockSmartSubordinate.java:47) ~[BlockSmartSubordinate.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more

**Comment by CptPatate** [comment]
I just saw that it causes intense lag when i tried, I had to reset my server afterwards and it was good again.

**Comment by H4nSolo** [comment]
Any Updates  to fix the problem?
My Friends has place the minesweeper block in our Base....
I have delete all blocks in Creative Mode but when i go over the Area from the old place i can see the Black Infobox.... and after a reconnect i have 1 Block.
No way to break in Survicle Mode and Gamemode 1 [CreativeMode]....

Sry but i think this Mod is a Bad Idea for this ModPack. 
To Many Bugs

**Comment by TimeConqueror** [comment]
Fixed in LootGames 1.0.3.1: https://github.com/TimeConqueror/LootGames-Issues/issues/4
