### ISSUE TITLE
Crash from Minecraft Launcher after 1.3.5 update

### ISSUE THREAD

**Issue by TenaciousTom** [adam9899/Issues#406]
11:54:43.812
Mixin config mixins.movingworld.json does not specify "minVersion" property
11:54:45.096
FML appears to be missing any signature data. This is not a good thing
11:54:45.305
Mixin config mixins.movingworld.json does not specify "minVersion" property
11:54:47.600
Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.minecraft.client.main.Main.main(SourceFile:38)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.creativemd.littletiles.LittleTilesTransformer@2d237460 from coremod LittlePatchingLoader
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 9 more
Caused by: java.lang.ClassCastException: org.objectweb.asm.tree.VarInsnNode cannot be cast to org.objectweb.asm.tree.LabelNode
	at com.creativemd.littletiles.LittleTilesTransformer$12.transform(LittleTilesTransformer.java:281)
	at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:43)
	at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:32)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 11 more
11:54:47.724
Process crashed with exit code 1

**Comment by ImJustJoshin** [comment]
I don't know what's happening with you but I'm pretty sure my update just got corrupted and I can't get it to grab and download the files without one of them screwing up, its a different mod failing every time.
Edit: Lost my saves and backups. A solution that works if you didn't lose your saves like I did is to make a new profile for MC Eternal 1.3.5 and just bring over a backup of your existing world into that profile then once you got everything you need to then just delete the old profile.
