### ISSUE TITLE
Constant crashing making it almost impossible to play. 

### ISSUE THREAD

**Issue by Freddy4258** [adam9899/Issues#49]
crashing numerous of my server players and hard crashing the server on occasion. i have been able to refine it down to dank null, midnight, and treasure 2.
one of many crash reports i have been getting. upon rejoining when i crash i get spammed with midnight errors and dank null errors along with that crash report.
https://paste.dimdev.org/alaqoxidul.mccrash

**Comment by iLovejesus123** [comment]
same

**Comment by laserlemons** [comment]
For a temporary fix you can set the rift spawn chance to 0 in Midnight's config file.

**Comment by radugrecu** [comment]
I'm getting the same thing
there are 945 *client.txt files in my crash-reports folder, all of which end with the following line

`  Suspected Mods: Midnight (midnight)`

The stack trace of the most recent one is

`java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): UnpooledSlicedByteBuf(ridx: 4, widx: 4, cap: 4/4, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 5, cap: 256))
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): UnpooledSlicedByteBuf(ridx: 4, widx: 4, cap: 4/4, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 5, cap: 256))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
    at com.mushroom.midnight.common.entity.RiftBridge.handleState(RiftBridge.java:150)
    at com.mushroom.midnight.common.network.MessageBridgeState$Handler.lambda$onMessage$0(MessageBridgeState.java:47)
    at com.mushroom.midnight.common.network.MessageBridgeState$Handler$$Lambda$8336/830401460.accept(Unknown Source)
    at com.mushroom.midnight.client.ClientProxy.lambda$handleMessage$1(ClientProxy.java:39)
    at com.mushroom.midnight.client.ClientProxy$$Lambda$8335/1437647925.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more`


944 of these files contain this method call `com.mushroom.midnight.common.entity.RiftBridge.handleState`

**Comment by dbulm2** [comment]
It's not The Midnight, I removed it due to the crashlog and the lag after a few hours (variable dependant on how hard my computer is working already, garbage collection issue?) still occurs.
After removing it, the error changed to Ice and Fire's chains, but the `java.util.concurrent.FutureTask.get` is the common link between everything I've seen, making me think that it means "we tried to do something, but the tick hasn't happened yet" (from the lag spike)
