### ISSUE TITLE
Error Message when I try to launch 

### ISSUE THREAD

**Issue by PPSB123** [adam9899/Issues#585]
After everything is downloaded and installed, I keep getting this error message and I am not sure how to fix it. 

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Avalonzo** [comment]
From doing a google search I found this is a problem relating to MAC OS make sure you latest java installed then go to twitch>settings>minecraft>java settings>java version>change it to the latest java version should 1.8.251 if java version is locked then change launcher from native to jar then select the latest java version.
