### ISSUE TITLE
Something wrong with my Java?

### ISSUE THREAD

**Issue by aaronaustin0** [adam9899/Issues#654]
I have a standard Minecraft 1.15.2 server running without issue on this PC, but anytime I launch LaunchServer.bat I am greeted with the following: 

```
C:\Server\Eternal (ServerPack 1.3.5.3)>java -Xms2G -Xmx6G -XX:PermSize=256m -Dfml.read.Timeout=560 -jar forge-1.12.2-14.23.5.2847-universal.jar nogui
OpenJDK 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

C:\Server\Eternal (ServerPack 1.3.5.3)>pause
Press any key to continue . . .
```

This does not generate the EULA for me to accept. 

I can run minecraft_server.1.12.2.jar to generate the EULA, but even then it does not like to run the forge-1.12.2-14.23.5.2847-universal.jar for whatever reason. 

I have both Java 8 and Java 11 on this machine. I changed .jar file association to default to latest version of Java 8 but that does not appear to be working. 

Any suggestions?

**Comment by aaronaustin0** [comment]
Found I was still using Open Source JDK for Java 11. Complete uninstall of all things java and reinstalling java 8-32bit and 64bitfixed this issue. 

I'd like to be able to use Java 11 if possible. Any suggestions?

**Comment by ogradyjd** [comment]
Forge and everything else would have to be compiled and tested with java 11.   In addition, there are differences between Oracle java, OpenJDK, JRockit, etc...  So it depends on how much testing the forge team can/will do. 

The bigger problem is that this pack is constructed for Forge for Mincraft 1.12, which is built for Java 8.   This means until the pack is built on Forge for Minecraft 1.14 or up, you're probably stuck with using Java 8.  You should be able to have both Java 8 and 11 on the same machine.  Assuming you're on Win10, this might help:
https://www.happycoders.eu/java/how-to-switch-multiple-java-versions-windows/
