### ISSUE TITLE
Cannot Launch: Exception in main thread: Possible Java version error?

### ISSUE THREAD

**Issue by CHarrison7** [adam9899/Issues#658]
Here's the full console log when I try to launch MC Eternal:

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I've tried installed Java JRE 8 and JDK 8, as I found that as a possible solution to a kinda similar issue. It did not work, however.

Any suggestions? I'm on the latest macOS version. Thanks!

**Comment by CHarrison7** [comment]
JDK 8u251 was installed, but I had to manually override the java executable that the launcher was using. 🤦‍♂️

**Comment by ogradyjd** [comment]
Look at my answer for #654.  I'm pretty sure this is the same thing, but the link at the bottom might help you managed multiple versions of Java on the same machine.
