### ISSUE TITLE
Creating a server on linux/debian results in error

### ISSUE THREAD

**Issue by youngrip** [adam9899/Issues#67]
Forgive me for anything I fail to mention, as I am new to the debian system and hosting on a vm in general. I'm trying to create an MC Eternal server for me and my friends on debian/linux and after a fresh install, launching the LaunchServer.bat file results in the error pasted below. I've tried several things such as deleting the session.lock file and reinstalling the entire instance, but I've had no luck. 

[07:41:10] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)

Caused by: java.lang.RuntimeException: Failed to check session lock, aborting
        at net.minecraft.world.storage.SaveHandler.setSessionLock(SaveHandler.java:76) ~[bfb.class:?]
        at net.minecraft.world.storage.SaveHandler.<init>(SaveHandler.java:54) ~[bfb.class:?]
        at net.minecraft.world.chunk.storage.AnvilSaveHandler.<init>(AnvilSaveHandler.java:18) ~[bey.class:?]
        at net.minecraft.world.chunk.storage.AnvilSaveConverter.getSaveLoader(SourceFile:84) ~[bez.class:?]
        at appeng.core.worlddata.WorldData.onServerAboutToStart(WorldData.java:130) ~[WorldData.class:?]
        at appeng.core.AppEng.serverAboutToStart(AppEng.java:259) ~[AppEng.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:859) ~[Loader.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:292) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:268) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[07:41:10] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify sun.reflect.GeneratedMethodAccessor10 (untransformed name: sun.reflect.GeneratedMethodAccessor10)
[07:41:10] [Server thread/ERROR] [minecraft/CrashReport]: Could not save crash report to ./crash-reports/crash-2019-12-31_07.41.10-server.txt
java.io.FileNotFoundException: ./crash-reports/crash-2019-12-31_07.41.10-server.txt (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_232]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_232]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_232]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_232]
        at net.minecraft.crash.CrashReport.saveToFile(CrashReport.java:256) [b.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:563) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[07:41:10] [Server thread/ERROR] [minecraft/MinecraftServer]: We were unable to save this crash report to disk.

**Comment by youngrip** [comment]
I forgot to mention this, but the first time I ran the LaunchServer.bat, the entire process worked smoothly and created the World file in the folder. After that, starting the server again will result in the error message above. After reinstalling the entire server files, I cannot get the World file and the same error as mentioned. 
I did the same process on my actual computer which runs windows, and it runs fine, which leads me to believe this is a linux bug, but I could be wrong.

**Comment by jlewismoss** [comment]
LaunchServer.bat is a dos script not a linux script.  I'm surprised it worked at all but using it on linux is likely the cause of the problem.

Try putting this in "startserver.sh":

#! /bin/sh

java -Xms2048m -Xmx4096m -XX:PermSize=256m -jar forge-1.12.2-14.23.5.2847-universal.jar nogui

---------------------------------

Then do "chmod +x startserver.sh" and "dos2unix startserver.sh"

Then run that script instead.

That's what I have running on my debian system.

**Comment by crazed014** [comment]
This is a bit older now, but in case you haven't gotten it worked out. Make sure you run it as sudo, the pack has a hard time with writing to files as standard user.
