### ISSUE TITLE
MC Eternal Shop Bug

### ISSUE THREAD

**Issue by Ne0nhigh** [adam9899/Issues#741]
Hello, i got a Osmium Ore and a Osmium Ingot. Now i would like to buy the Osmium Ingot but i cant. When i press on it no osmium appair to my inventory. 

Mc Eternal Version 1.3.6

![osmium](https://user-images.githubusercontent.com/53381437/88463918-b25c8900-ceb6-11ea-8d33-b6f2b5eff55c.PNG)

I thinks this is the error 

[K[31;1m[20:41:22] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at com.feed_the_beast.mods.money.shop.ShopEntry.isUnlocked(ShopEntry.java:120) ~[ShopEntry.class:?]
at com.feed_the_beast.mods.money.net.MessageBuy.onMessage(MessageBuy.java:71) ~[MessageBuy.class:?]
at com.feed_the_beast.ftblib.lib.net.MessageToServerHandler.lambda$onMessage$0(MessageToServerHandler.java:27) ~[MessageToServerHandler.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
... 5 more

but i dont know what this say :( i maked the achievement. I have osmium ore and ingot.

I know the other threads but i dont find a fix for it sry.

i hope someone can help me

**Comment by HadesDurin** [comment]
i recommend you update your java to latest edition B261 at the moment and try again, also update the server and your cliebt with latest pack 1.3.7.1
