### ISSUE TITLE
Null Pointer Exception when entering deep dark

### ISSUE THREAD

**Issue by ShyAssassin** [adam9899/Issues#955]
Extra Utilities crashes a server and or client when a player goes into the deep dark issue effects both server and local saves.
the Error is as follows
```
java.lang.NullPointerException
    at net.minecraft.world.Teleporter.<init>(Teleporter.java:27)
    at com.rwtema.extrautils2.dimensions.TeleporterBase.<init>(TeleporterBase.java:25)
    at com.rwtema.extrautils2.dimensions.deep_dark.TeleporterDeepDark.<init>(TeleporterDeepDark.java:13)
    at com.rwtema.extrautils2.backend.entries.XU2Entries$68.createTeleporter(XU2Entries.java:1277)
    at com.rwtema.extrautils2.blocks.BlockTeleporter$EventHandler.processMap(BlockTeleporter.java:231)
    at com.rwtema.extrautils2.blocks.BlockTeleporter$EventHandler.worldTick(BlockTeleporter.java:175)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1730_EventHandler_worldTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```
[crash-2021-03-13_19.05.44-server.txt](https://github.com/adam9899/Issues/files/6136413/crash-2021-03-13_19.05.44-server.txt)

**Comment by ShyAssassin** [comment]
after looking around for a bit i found that the deep dark is disabled in `extrautils2.cfg`
not sure if this is intentional but if anybody else has this issue here is the fix
